<?php

$auto_Cutoff = '';
$auto_Cutoff .= ':global datetime '; 
$auto_Cutoff .= ';:global expiredate '; 
$auto_Cutoff .= ';:global datenum '; 
$auto_Cutoff .= ';:global expirenum '; 
$auto_Cutoff .= ';:local montharray ( "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec" ) '; 
$auto_Cutoff .= ';:local date [ /system clock get date ] '; 
$auto_Cutoff .= ';:local day [ :pick $date 4 6 ] '; 
$auto_Cutoff .= ';:local monthtext [ :pick $date 0 3 ] '; 
$auto_Cutoff .= ';:local month ( [ :find $montharray $monthtext ] + 1) '; 
$auto_Cutoff .= ';:local year [ :pick $date 7 11 ] '; 
$auto_Cutoff .= ';:if ($month < 10) do={:set month ("0" . $month);}; '; 
$auto_Cutoff .= ';:local timetext [ /system clock get time ] '; 
$auto_Cutoff .= ';:local hour [ :pick $timetext 0 2 ] '; 
$auto_Cutoff .= ';:local minute [ pick $timetext 3 5 ] '; 
$auto_Cutoff .= ';:local second [ pick $timetext 6 8 ] '; 
$auto_Cutoff .= ';:set datetime ( $year . $month . $day . $time . $hour . $minute . $second ) '; 
$auto_Cutoff .= ';:set datenum [ :tonum $datetime ] '; 
$auto_Cutoff .= ';:foreach i in [ /ip hotspot user find where disabled=no ] do={ '; 
$auto_Cutoff .= ';:local usercomment [ /ip hotspot user get $i comment ] '; 
$auto_Cutoff .= ';:local username [ /ip hotspot user get $i name ] '; 
$auto_Cutoff .= ';:if ( [ :find $usercomment "expire" ] = 0 ) do={ '; 
$auto_Cutoff .= ';:local expire [ :pick $usercomment 7 26 ] '; 
$auto_Cutoff .= ';:local expireyear [ :pick $expire 0 4 ] '; 
$auto_Cutoff .= ';:local expiremonth [ :pick $expire 5 7 ] '; 
$auto_Cutoff .= ';:local expireday [ :pick $expire 8 10 ] '; 
$auto_Cutoff .= ';:local expirehour [ :pick $expire 11 13 ] '; 
$auto_Cutoff .= ';:local expireminute [ :pick $expire 14 16 ] '; 
$auto_Cutoff .= ';:local expiresecond [ :pick $expire 17 19 ] '; 
$auto_Cutoff .= ';:set expiredate ( $expireyear . $expiremonth . $expireday . $expirehour . $expireminute . $expiresecond ) '; 
$auto_Cutoff .= ';:set expirenum [ :tonum $expiredate ] '; 
$auto_Cutoff .= ';:if ( $datenum > $expirenum ) do={ '; 
$auto_Cutoff .= ';:log info "HOTSPOT EXPIRE SCRIPT: Disabling Hotspot user $name first logged in $date" '; 
$auto_Cutoff .= ';:local expirecomment ("This user expire @" . $expireyear . "-" . $expiremonth . "-" . $expireday . " " . $expirehour . ":" .$expireminute . ":" . $expiresecond ) '; 
$auto_Cutoff .= ';[ /ip hotspot user disable $i ] ';
$auto_Cutoff .= ';[ /ip hotspot user set $i comment=$expirecomment ] ';
$auto_Cutoff .= ';[ /ip hotspot active remove [ find where user=$username] ] }}}';
